const LIGHT_YELLOW = "F5FF73";

const StyleConfig = {
    // APP_NAME: "Metal Detector",
    VICTORY_OVERLAY_LABEL: "Overlay",
    TOGGLE_FRACTAL_HIGH_LABEL: "Highs",
    TOGGLE_FRACTAL_LOW_LABEL: "Lows",
    SHOW_GRAPH_LABEL: "Graph",
    HIDE_GRAPH_LABEL: "Back",
    GREEN_GREEN: "00FE20",
    RED_RED: "FE0000",
    DATE_TITLE_BACKGROUND_COLOR: "D9FE7F",
    PRICE_TITLE_BACKGROUND_COLOR: "F14FFD",
    HIGH_TITLE_BACKGROUND_COLOR: "BFFFF6",
    LOW_TITLE_BACKGROUND_COLOR: "C7BFFF",
    DATE_COLUMN_BACKGROUND_COLOR: "F6FF98",
    PRICE_COLUMN_BACKGROUND_COLOR: "7FCDFE",
    // HIGH_COLUMN_BACKGROUND_COLOR:"FDD44F",
    // LOW_COLUMN_BACKGROUND_COLOR:"FFBFC8",
    HIGH_COLUMN_BACKGROUND_COLOR: undefined,
    LOW_COLUMN_BACKGROUND_COLOR: undefined,
    DATE_COLUMN_WIDTH: 14,
    PRICE_COLUMN_WIDTH: 9,
    HIGH_COLUMN_WIDTH: 9,
    LOW_COLUMN_WIDTH: 9,
    EMPTY_COLUMN_WIDTH: 4,
    MAIN_FONT: "Arial",
    MAIN_TEXT_HORIZONTAL_ALIGNMENT: "center",
    EXCEL_INPUT_BUTTON_TEXT: "Excel Input",
    FRACTAL_INPUT_BUTTON_TEXT: "Fractal Input",
    DOWNLOAD_BUTTON_TEXT: "Download",
    
}
export default StyleConfig