const Constants = {
    DATE_TITLE_BACKGROUND_COLOR: "D9FE7F",
    PRICE_TITLE_BACKGROUND_COLOR: "F14FFD",
    DATE_COLUMN_BACKGROUND_COLOR: "FDD44F",
    PRICE_COLUMN_BACKGROUND_COLOR: "7FCDFE",
    DATE_COLUMN_WIDTH: 14,
    PRICE_COLUMN_WIDTH: 9,
    EMPTY_COLUMN_WIDTH: 3,
    MAIN_FONT: "Arial",
    MAIN_TEXT_HORIZONTAL_ALIGNMENT: "center",
    
}
export default Constants