const LIGHT_YELLOW = "F5FF73";

const StyleConfig = {
    // Labels
    LABEL_API_BUTTON: "API",
    LABEL_ZOOM_BUTTON: "Zoom",
    LABEL_TOOLTIP_BUTTON: "Tooltip",
    LABEL_SELECTED_DATE_OVERLAY: "Loaded",
    LABEL_SELECT_ME: "Selected",
    LABEL_LOAD_OVERLAY: "Load Overlay",
    LABEL_ADD_BUTTON: "Add",
    LABEL_SUBTRACT_BUTTON: "Subtract",
    LABEL_FOLDER_INPUT: "Folder",
    DISPLAY_OVERLAY_LABEL: "Toggle Overlay",
    VICTORY_OVERLAY_LABEL: "Load Singular Overlay By File",
    TOGGLE_FRACTAL_HIGH_LABEL: "Highs",
    TOGGLE_FRACTAL_LOW_LABEL: "Lows",
    SHOW_GRAPH_LABEL: "Graph",
    HIDE_GRAPH_LABEL: "Back",
    EXCEL_INPUT_BUTTON_TEXT: "Excel Input",
    FRACTAL_INPUT_BUTTON_TEXT: "Fractal Input",
    DOWNLOAD_BUTTON_TEXT: "Download",

    // Placeholders
    PLACEHOLDER_CHUNK_AMOUNT: "Chunk Amount",
    PLACEHOLDER_START_DATE: "Start Date",
    PLACEHOLDER_END_DATE: "End Date",
    PLACEHOLDER_TICKER_SYMBOL: "Symbol",

    // Colors
    GREEN_GREEN: "00FE20",
    RED_RED: "FE0000",
    DATE_TITLE_BACKGROUND_COLOR: "D9FE7F",
    PRICE_TITLE_BACKGROUND_COLOR: "F14FFD",
    HIGH_TITLE_BACKGROUND_COLOR: "BFFFF6",
    LOW_TITLE_BACKGROUND_COLOR: "C7BFFF",
    DATE_COLUMN_BACKGROUND_COLOR: "F6FF98",
    PRICE_COLUMN_BACKGROUND_COLOR: "7FCDFE",
    // HIGH_COLUMN_BACKGROUND_COLOR:"FDD44F",
    // LOW_COLUMN_BACKGROUND_COLOR:"FFBFC8",
    HIGH_COLUMN_BACKGROUND_COLOR: undefined,
    LOW_COLUMN_BACKGROUND_COLOR: undefined,

    // Column Sizes
    DATE_COLUMN_WIDTH: 14,
    PRICE_COLUMN_WIDTH: 9,
    HIGH_COLUMN_WIDTH: 9,
    LOW_COLUMN_WIDTH: 9,
    EMPTY_COLUMN_WIDTH: 4,

    // Fonts
    MAIN_FONT: "Arial",

    // Alignments
    MAIN_TEXT_HORIZONTAL_ALIGNMENT: "center",
}
export default StyleConfig